sources:
  - name: JadeFC
    handler:
      openapi:
        source: ./schemas/jade-openapi.yaml
        baseUrl: http://a856e7a1e733b4d4192ca8d3341790e6-126565715.ap-southeast-2.elb.amazonaws.com/JadeRestSite/jadehttp.dll
        customFetch: ./jade-fetch.ts

  - name: Transactions
    handler:
      graphql:
        endpoint: ./schemas/transactions.graphql

require:
  - ts-node/register/transpile-only

additionalTypeDefs: |
    extend type FCAccount {
      transactions: TransactionContainer!
    }

additionalResolvers:
  - ./resolvers/transactions.ts

cache:
    inmemoryLRU:
        max: 5000

serve:
  browser: false
  hostname: 0.0.0.0
  playground: true

