sources:
  - name: JadeFC
    handler:
      openapi:
        source: ./schemas/jade-openapi.yaml
        # Update the host name part of the URL to match the EXTERNAL-IP for the iis-service in the K8s cluster
        # The EXTERNAL-IP  can be obtained by running 'kubectl get svc' from a command shell
        baseUrl: http://acf5764ad19524ee480a946f65f3821e-900662398.ap-southeast-2.elb.amazonaws.com/JadeRestSite/jadehttp.dll
        customFetch: ./jade-fetch.ts

  - name: Transactions
    handler:
      graphql:
        endpoint: ./schemas/transactions.graphql

require:
  - ts-node/register/transpile-only

additionalTypeDefs: |
    extend type FCAccount {
      transactions: TransactionContainer!
    }

additionalResolvers:
  - ./resolvers/transactions.ts

cache:
    inmemoryLRU:
        max: 5000

serve:
  browser: false
  hostname: 0.0.0.0
  playground: true

