apiVersion: v1
kind: Service
metadata:
  name: fin-rap
spec:
  ports:
  - port: 9901
  selector:
    app: fin-rap
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-rap
spec:
  selector:
    matchLabels:
      app: fin-rap
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: fin-rap
    spec:
      containers:
      - image: public.ecr.aws/p5o1m4j3/fin-demo/db-server:20.0.02-U
        name: fin-rap
        ports:
        - containerPort: 9901
          name: fin-rap
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: rap-database-volume
            mountPath: c:\jade\system
      nodeSelector:
        kubernetes.io/os: windows
      volumes:
      - name: rap-database-volume
        persistentVolumeClaim:
           claimName: ebs-windows-pv-claim
