apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis
spec:
  selector:
    matchLabels:
      app: iis
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: iis
        tier: backend
        track: stable
    spec:
      containers:
      - name: iis
        image: public.ecr.aws/p5o1m4j3/fin-demo/iis:v2
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: iis-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: iis
    tier: backend
    track: stable
  sessionAffinity: None
  type: LoadBalancer