# demo cluster.yaml
# An example ClusterConfig containing a Windows and a Linux node group
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jug-demo-cluster
  region: ap-southeast-2

nodeGroups:
  - name: windows-ng
    amiFamily: WindowsServer2019FullContainer
    instanceType: t3.medium
    desiredCapacity: 1
  - name: linux-ng
    instanceType: t3.small
    desiredCapacity: 1